### ISSUE TITLE
ModInfo checker

### ISSUE THREAD

**Issue by nestquik** [GandaG/fomod-validator#1]
Do u have any information about ModInfo.xml file?
We can have there Description, Name, Version, Latest Known Version, CategoryID, DownloadID on Nexus, ModID on Nexus, URL, what else?
![image](https://cloud.githubusercontent.com/assets/10574210/15274590/7df6b466-1abe-11e6-8cfb-a7a48ad26af4.png)

**Comment by GandaG** [comment]
Not really, and it's not really worth the time to build a schema to validate it, since most options have no logical implication and MO mostly ignores them. For all I know, NMM doesn't even use any of it.
